[build]
  command = "npm run build"
  publish = "build" 

[deploy]
  edge_handlers = true 
  provider = "netlify"
  site = "zyharz.netlify.app"
  auth = { api_token = { secrets = ["NETLIFY_API_TOKEN"] } }

[[redirects]]
  from = "/*" 
  to = "/index.html"
  status = 200 

[env]
  API_KEY = "your-api-key"
  BASE_URL = "https://api.example.com"

[[plugins]]
  package = "netlify-plugin-env"

[[plugins]]
  package = "netlify-plugin-inline-source"

[[plugins]]
  package = "netlify-plugin-gzip"